apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "beep-rtc.fullname" .) }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.portHTTP }}
      protocol: TCP
      name: http
    {{- range .Values.ports }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
      name: port-{{ . }}
    {{- end }}
  selector:
    {{- include "beep-rtc.selectorLabels" . | nindent 4 }}
