{
 "title": "Logs from transport",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs from main",
   "type": "table",
   "gridPos": { "h": 15, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{application=\"beep-sfu\", source=\"main\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs from signalling",
   "type": "table",
   "gridPos": { "h": 18, "w": 20, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{application=\"beep-sfu\", source=\"signalling_server\"}"
    }
   ]
  },
  {
   "title": "Logs from transport",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{application=\"beep-sfu\", source=\"transport\"} | json timestamp=\"timestamp\", level=\"level\", message=\"fields.message\", port=\"span.port\""
    }
   ]
  }
 ]
}