replicaCount: 1
imagePullSecrets:
  - name: beep-registry
image:
  repository: gitlab.polytech.umontpellier.fr:5050/beep/front/beep-rtc
  pullPolicy: Always
  tag: 1.0.1
  portHTTP: 8080
  portUDPmin: 5060
  portUDPmax: 5060

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: { traefik.ingress.kubernetes.io/router.entrypoints: web}
  hosts:
    - host: api-visio.duratm.com
      paths: ['/']

resources: {}
ports:
  - 5060
