replicaCount: 1
imagePullSecrets:
  - name: beep-registry
image:
  repository: gitlab.polytech.umontpellier.fr:5050/beep/front/beep-rtc
  pullPolicy: Always
  tag: latest
  portHTTP: 8080
  portUDPmin: 3000
  portUDPmax: 3020

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations: { traefik.ingress.kubernetes.io/router.entrypoints: web}
  hosts:
    - host: api-visio.duratm.com
      paths: ['/']

resources: {}
ports:
  - 3000
  - 3001
  - 3002
  - 3003
  - 3004
  - 3005
  - 3006
  - 3007
  - 3008
  - 3009
  - 3010
  - 3011
  - 3012
  - 3013
  - 3014
  - 3015
  - 3016
  - 3017
  - 3018
  - 3019
  - 3020