replicaCount: 1
imagePullSecrets:
  - name: beep-registry
image:
  repository: gitlab.polytech.umontpellier.fr:5050/beep/front/beep-rtc
  pullPolicy: Always
  tag: latest
  portHTTP: 8080
  portUDPmin: 3000
  portUDPmax: 3001

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations: { traefik.ingress.kubernetes.io/router.entrypoints: web}
  hosts:
    - host: api-visio.duratm.com
      paths: ['/']

resources: {}
ports:
  - 3000
  - 3001